x-app: &app
  build: .
  env_file:
    - .env
  restart: unless-stopped

services:
  web:
    <<: *app
    environment:
      RUN_MIGRATIONS: "true"
    ports:
      - "${PORT:-8080}:8080"
    command: ["web"]

  queue:
    <<: *app
    environment:
      RUN_MIGRATIONS: "false"
    command: ["queue"]

  scheduler:
    <<: *app
    environment:
      RUN_MIGRATIONS: "false"
    command: ["scheduler"]
